on: [push, pull_request]
name: test
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.14.x

    - name: Install dependencies
      run: |
        sudo apt install -y \
          ninja-build \
          libssl-dev \
          libprotobuf-dev \
          protobuf-compiler
  
    - name: Compile GameNetworkingSockets library
      run: |
        cd lib/GameNetworkingSockets
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        echo "LD_LIBRARY_PATH=$(pwd)/bin:${LD_LIBRARY_PATH}" >> $GITHUB_ENV

    - name: Run tests
      run: go test -v


  test-windows:
    runs-on: windows-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install msys2
      uses: msys2/setup-msys2@v2
      with:
        path-type: inherit
        update: true
        msystem: MINGW64
        install: >-
          curl
          git
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-go
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-openssl
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-protobuf
  
    - name: Compile GameNetworkingSockets library
      run: |
        set MSYSTEM=mingw64
        cd lib/GameNetworkingSockets
        mkdir build
        cd build
        msys2 cmake -G Ninja ..
        msys2 ninja
        cp bin/libGameNetworkingSockets.dll ../../..

    - name: Run tests
      run: | 
        set MSYSTEM=MINGW64
        msys2 go test -v
