on: [push, pull_request]
name: test
jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.14.x

    - name: Install dependencies
      run: |
        sudo apt install -y \
          ninja-build \
          libssl-dev \
          libprotobuf-dev \
          protobuf-compiler
  
    - name: Compile GameNetworkingSockets library
      run: |
        cd lib/GameNetworkingSockets
        mkdir build
        cd build
        cmake -G Ninja ..
        ninja
        echo "LD_LIBRARY_PATH=$(pwd)/bin:${LD_LIBRARY_PATH}" >> $GITHUB_ENV

    - name: Run tests
      run: go test -v